sonar.projectKey=ccitproject
sonar.projectName=CCIT Docker Application

sonar.sources=.
sonar.tests=tests

sonar.exclusions=tests/**,**/.git/**,**/.github/**,**/__pycache__/**,**/.pytest_cache/**,**/venv/**,**/.venv/**

sonar.python.version=3.12