sonar.projectKey=ccitproject
sonar.projectName=CCIT Docker Application

sonar.sources=app.py
sonar.tests=tests

sonar.exclusions=**/.git/**,**/.github/**,**/__pycache__/**,**/.pytest_cache/**,**/venv/**,**/.venv/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml