sonar.projectKey=ccitproject
sonar.projectName=CCIT Docker Application

sonar.sources=.
sonar.tests=tests

sonar.python.version=3.12

sonar.exclusions=**/.git/**,**/.github/**,**/__pycache__/**,**/.pytest_cache/**,**/venv/**,**/.venv/**